In [1]:
import re
from pypdf import PdfReader
import pandas as pd

In [2]:
reader = PdfReader("Ed_30_PAS_3_2020_2022_Res_Final_Tipo D_Redação.pdf")
number_of_pages = len(reader.pages)

In [3]:
number_of_pages

297

In [4]:
text_list = []
for i in range(number_of_pages):
    text_list.append(reader.pages[i].extract_text())

In [5]:
len(text_list)

297

In [6]:
text = ''.join(text_list)

In [8]:
len(text)

1572415

In [9]:
text = re.sub(r" [0-9]+ \n", "", text)
text = re.sub(r"\n", "", text)
text = re.sub(r"^.*?(2\.1\.1 *)", r"\1", text)
text = re.sub(r"\*[^*]*$", "", text)

In [11]:
# cutting the end
text = re.sub('\. \* Cursos que exigem.*', "", text)

In [12]:
string_sample = '2.1.1 CAMPUS  DARCY RIBEIRO – DIURNO  ADMINISTRAÇÃO (BACHARELADO)  20199023, Amanda Amorim Luz, 5.172, 14.653, 6.947, 3.845, 19.994, 7.222, 4.998, 16.660, 8.060, 2.1.3 CAMPUS  UNB CEILÂNDIA (FCE)  ENFERMAGEM (BACHARELADO)  20186508, Adrielle Moreira de Carvalho Lopes, 2.586, 17.526, 7.000, 2.307, 20.249, 5.412, 2.142,'

In [13]:
# split by course
pattern = r'\. (?=[A-Z]|\d\.)'
text_split = re.split(pattern=pattern, string=text)
#sections = [section for section in text_split if section.strip()]

In [14]:
len(text_split)

121

In [15]:
# weirdly some numeros de inscricao were broken into 6 digits + blank space + 2 digits, so we unite now
pattern = r"(\d{6})\s+(\d{2})"
sections = [re.sub(pattern, r"\1\2", section.strip()) for section in text_split]

In [16]:
def get_course_grades(my_string: str) -> tuple:
    
    pattern = "^(.*?)\d{8}, "

    result = re.search(pattern, my_string)
    if result:
        extracted_text = result.group(1)
        print(extracted_text)
    
    #course_dict = {}
    students = re.sub(re.escape(extracted_text), "", my_string)
    students = re.split(pattern=' /', string=students)
    
    #course_dict[extracted_text] = students

    return (extracted_text, students)

In [17]:
def convert_to_dataframe(my_tuple: tuple) -> pd.DataFrame:
    df = pd.Series(my_tuple[1])
    df = df.str.split(',', expand=True)
    df['course'] = my_tuple[0]
    return df

In [18]:
len(sections)

121

In [19]:
df_course = list()

for i in range(len(sections)):
    
    course = get_course_grades(sections[i])
    course = convert_to_dataframe(course)

    df_course.append(course)
    print(len(df_course))

2.1.1 CAMPUS  DARCY RIBEIRO – DIURNO  ADMINISTRAÇÃO (BACHARELADO)
1
ADMINISTRAÇÃO (BACHARELADO) – SUB JUDICE
2
AGRONO MIA (BACHARELADO)
3
AGRONOMIA (BACHARELADO) – SUB JUDICE
4
ARQUITETURA E URBANISMO (BACHARELADO)
5
ARTES CÊNICAS - INTERPRETAÇÃO TEATRAL (BACHARELADO) *
6
ARTES VISUAIS (BACHARELADO)*
7
ARTES VISUAIS (LICENCIATURA)*
8
BIBLIOTECONOMIA (BACHARELADO)
9
BIOTECNOLOGIA (BACHARELADO)
10
CIÊNCIA DA COMPUTAÇÃO (BACHARELADO)
11
CIÊNC IA DA COMPUTAÇÃO (BACHARELADO) – SUB JUDICE
12
CIÊNCIA POLÍTICA (BACHARELADO)
13
CIÊNCIAS BIOLÓGICAS (BACHARELADO)
14
CIÊNCIAS CONTÁBEIS (BACHARELADO)
15
CIÊNCIAS ECONÔMICAS (BACHARELADO)
16
CIÊNCIAS SOCIAIS – ANTROPOLOGIA / SOCIOLOGIA (BACHARELADO/LICENCIATURA)
17
COMUNICAÇÃO SOCIAL – AUDIOVISUAL (BACHARELADO)
18
COMUNICAÇÃO SOCI AL – AUDIOVISUAL (BACHARELADO) – SUB JUDICE
19
COMUNICAÇÃO SOCIAL - PUBLICIDADE E PROPAGANDA (BACHARELADO)
20
DESIGN – PROGRAMAÇÃO VISUAL/PROJETO DO PRODUTO (BACHARELADO)
21
DIREITO (BACHARELADO)
22
DIREITO (BACHARELADO) – SUB JUDICE
23
EDUCAÇÃO FÍSICA (BACHARELADO)
24
EDUCAÇÃO FÍSICA (BACHARELA DO) – SUB JUDICE
25
EDUCAÇÃO FÍSICA (LICENCIATURA)
26
EDUCAÇÃO FÍSICA (LICENC IATURA) – SUB JUDICE
27
ENFERMAGEM (BACHARELADO)
28
ENGENHARIA AMBIENTAL (BACHARELADO)
29
ENGENHARIA CIVIL (BACHARELADO)
30
ENGENHARIA DE COMPUTAÇÃO (BACHARELADO)
31
ENGENHARIA DE REDES DE COMUNICAÇÃO (BACHARELADO)
32
ENGENHARIA ELÉTRICA (BACHARELADO)  20197 010, Ana Teresa Camargos Falcao, 6.034, 55.455, 9.517, 2.307, 57.914, 9.600, 6.426, 52.360, 9.667, 127.062, 4, -, -, -, -, -, -, -, -, - /
33
ENGENHARIA FLORESTAL (BACHARELADO)
34
ENGENHARIA MECÂNICA (BACHARELADO)
35
ENGENHARIA MECATRÔNICA – CONTROLE E AUTOMAÇÃO (BACHARELADO)
36
ENGENHARIA MECATRÔNICA – CONT ROLE E AUTOMAÇÃO (BACHARELADO) – SUB JUDICE
37
ENGENHARIA QUÍMICA (BACHARELADO)
38
ESTATÍSTICA (BACHARELADO)
39
FARMÁCIA (BACHARELADO)
40
FILOSOFIA (BACHARELADO/LICENCIATURA)
41
FÍSICA (BACHARELADO)
42
GEOFÍSICA (BACHARELADO)
43
GEOGRAFIA (BACHARELADO/LICENCIATURA)
44
GEOLOGIA (BACHARELADO)
45
HISTÓRIA (BACHARELADO/LICENCIATURA )
46
JORNALISMO (BACHARELADO)
47
LETRAS – PORTUGUÊS DO BRASIL COMO SEGUNDA LÍNGUA (LICENCIATURA)
48
LETRAS – TRADUÇÃO – FRANCÊS (BACHARELADO)
49
LETRAS – TRADUÇÃO – INGLÊS  (BACHARELADO)
50
LETRAS – TRADUÇÃO – INGLÊS (BACHARELADO) – SUB JUDICE
51
LICENCIATURA EM ARTES CÊNICAS*
52
LÍNGUA ESTRANGEIRA APLICADA – MULTILINGUISMO E SOCIEDADE DA INFORMAÇÃO (BACHARELADO)
53
LÍNGUA FRANCESA E RESPECTIVA LITERATURA (BACHARELADO/LICENCIATURA)
54
LÍNGUA INGLESA E RES PECTIVA LITERATURA (BACHARELADO/LICENCIATURA)
55
LÍNGUA PORTUGUESA E RESPECTIVA LITERATURA (BACHARELADO/LICENCIATURA)
56
LÍNGUA PORTUGUESA E RESPECTIVA LITERAT URA (BACHARELADO/LICENCIATURA) – SUB JUDICE
57
MATEMÁTICA (BACHARELADO/LICENCIATURA)
58
MEDICINA (BACHARELADO)
59
MEDICINA (BACHARELADO) – SUB JUDICE
60
MEDICINA VETERINÁRIA (BACHARELADO)
61
MUSEOLOGIA (BACHARELADO)
62
MÚSICA (BACHARELADO)*
63
MÚSICA (LICENCIATU RA)*
64
NUTRIÇÃO (BACHARELADO)
65
NUTRIÇÃO (BACHARELADO) – SUB JUDICE
66
ODONTOLOGIA (BACHARELADO)
67
PEDAGOGIA (LICENCIATURA)
68
PSICOLOGIA (BACHARELADO / LICENCIATURA / PSICÓLOGO)
69
PSICOLOGIA (BACHARELADO / LICENCIATURA / PSICÓLOGO ) – SUB JUDICE
70
QUÍMICA (BACHARELADO)
71
QUÍMICA TECNOLÓGICA (BACHARELADO)
72
RELAÇÕES INTERNACIONAIS (BACHARELADO)
73
RELAÇÕE S INTERNACIONAIS (BACHARELADO) – SUB JUDICE
74
SERVIÇO SOCIAL (BACHARELADO)
75
TURISM O (BACHARELADO)
76
2.1.2 CAMPUS  DARCY RIBEIRO – NOTURNO  ADMINISTRAÇÃO (BACHARELADO)
77
ARQUITETURA E URBANISMO (BACHARELADO)
78
ARQUIVOLOGIA (BACHARELADO)
79
CIÊNCIAS AMBIENTAIS (BACHARELADO)
80
CIÊNCIAS CONTÁBEIS (BACHARELADO)
81
COMPUTAÇÃO (LICENCIATURA)
82
COMPUTAÇÃO (LICENCIATURA) – SUB JUDICE
83
COMUNICAÇÃO ORGANIZACIONAL (BACHARELADO)
84
DIREITO (BACHARELADO)
85
DIREITO (BACHARE LADO) – SUB JUDICE
86
ENGENHARIA DE PRODUÇÃO (BACHARELADO)
87
ENGENH ARIA DE PRODUÇÃO (BACHARELADO) – SUB JUDICE
88
FARMÁCIA (BACHARELADO)
89
FILOSOFIA (LICENCIATURA)
90
GESTÃO DE AGRONEGÓCIO (BACHARELADO)
91
GESTÃO DE POLÍTICAS PÚB LICAS (BACHARELADO)
92
HISTÓRIA (LICENCIATURA)
93
LETRAS – TRADUÇÃO E SPANHOL (BACHARELADO)
94
LICENCIATURA EM CIÊNCIAS BIOLÓGICAS
95
LICENCIATURA EM FÍSICA
96
LICENCIATURA EM MATEMÁTICA
97
LICENCIATURA EM QUÍMICA
98
LÍNGUA E LITERATURA JAPONESA (LICENCIATURA)
99
LÍNGUA ESPANHOLA E LITERATURA ESPANHOLA E HISPANO -AMERICANA (LICENCIATURA)
100
LÍNGUA PORTUGUESA E RESPECTIVA LITERATURA (LICENCIATURA)
101
PEDAGOGIA (LICENCIATURA)
102
SAÚDE COLETIVA (BACHARELADO)
103
SERVIÇO SOCIAL (BACHARELADO)
104
TEORIA, CRÍTICA E HISTÓRIA DA ARTE (BACHARELADO)
105
2.1.3 CAMPUS  UNB CEILÂNDIA (FCE)  ENFERMAGEM (BACHARELADO)
106
ENFERMAGEM (BACHARELADO) – SUB JUDICE
107
FARMÁCIA (BACHARELADO)
108
FARMÁCIA (BACHARELADO) – SUB JUDICE
109
FISIOTERAPIA (BACHARELADO)
110
FISIOTERAPIA (BACHARELADO) – SUB JUDICE
111
FONOAUDIOLOGIA (BACHARELADO)
112
SAÚDE COLETIVA (BACHARELADO)
113
SAÚDE COLETIVA (BACHARELADO) – SUB JUDICE
114
TERAPIA OCUPACIONAL (BACHARELADO)
115
2.1.4 CAMPUS  UNB GAMA (FGA)  ENGENHARIAS – AEROESPACIAL / AUTOMOTIVA / ELETRÔNICA / ENERGIA / SOFTWARE (BACHARELADOS)**
116
ENGENHARIAS – AEROESPACIAL / AUTOMOTIVA / ELETRÔNICA / ENERG IA / SOFTWARE (BACHARELADOS)** – SUB JUDICE
117
2.1.5  CAMPUS  UNB PLANALTINA (FUP) – DIURNO  CIÊNCIAS NATURAIS (L ICENCIATURA)
118
GESTÃO DO AGRONEGÓCIO (BACHARELADO)
119
2.1.6  CAMPUS  UNB PLANALTINA (FUP) – NOTURNO  CIÊNCIAS NATURAI S (LICENCIATURA)
120
GESTÃO AMBIENTAL (BACHARELADO)
121

In [ ]:
pattern = "^(.*?)\d{8}, "

result = re.search(pattern, my_string)
if result:
    extracted_text = result.group(1)
    print(extracted_text)

#course_dict = {}
students = re.sub(re.escape(extracted_text), "", my_string)
students = re.split(pattern=' /', string=students)

In [20]:
teste = pd.concat(df_course)

In [24]:
teste.shape

(7300, 23)

In [36]:
COLUMN_NAMES = ['numero_inscricao',
                'nome',
                'escore_bruto_p1_etapa1',
                'escore_bruto_p2_etapa1',
                'nota_redacao_etapa1',
                'escore_bruto_p1_etapa2',
                'escore_bruto_p2_etapa2',
                'nota_redacao_etapa2',
                'escore_bruto_p1_etapa3',
                'escore_bruto_p2_etapa3',
                'nota_redacao_etapa3',
                'argumento_final',
                'classificacao_final_universal',
                'classificacao_final_cotas_negros',
                'classificacao_final_publicas1',
                'classificacao_final_publicas2',
                'classificacao_final_publicas3',
                'classificacao_final_publicas4',
                'classificacao_final_publicas5',
                'classificacao_final_publicas6',
                'classificacao_final_publicas7',
                'classificacao_final_publicas8',
                'course']

In [37]:
teste.columns = COLUMN_NAMES

In [39]:
teste.tail()

,numero_inscricao,nome,escore_bruto_p1_etapa1,escore_bruto_p2_etapa1,nota_redacao_etapa1,escore_bruto_p1_etapa2,escore_bruto_p2_etapa2,nota_redacao_etapa2,escore_bruto_p1_etapa3,escore_bruto_p2_etapa3,...,classificacao_final_cotas_negros,classificacao_final_publicas1,classificacao_final_publicas2,classificacao_final_publicas3,classificacao_final_publicas4,classificacao_final_publicas5,classificacao_final_publicas6,classificacao_final_publicas7,classificacao_final_publicas8,course
2,21270449,Sarah de Oliveira Nascimento,0.000,0.000,0.000,3.845,23.581,5.207,2.142,7.376,...,-,-,-,-,-,-,-,-,-,2.1.6 CAMPUS UNB PLANALTINA (FUP) – NOTURNO ...
0,20102521,Eloisa Graziele Rodrigues de Ara ujo,2.586,20.973,6.367,4.614,24.095,3.880,0.238,27.369,...,-,-,-,-,-,-,-,-,-,GESTÃO AMBIENTAL (BACHARELADO)
1,20190553,Julia de Sousa Vale,4.310,41.663,9.538,1.538,25.472,9.481,4.284,33.082,...,-,-,-,-,-,-,-,-,-,GESTÃO AMBIENTAL (BACHARELADO)
2,21208412,Manuella Stephanye Silva Magalhaes,0.000,0.000,0.000,3.845,35.068,7.308,3.570,24.752,...,-,-,-,-,-,-,-,1,-,GESTÃO AMBIENTAL (BACHARELADO)
3,20198986,Mateus Filipi Correia Silva,0.287,11.491,5.630,4.870,16.500,4.413,0.714,17.610,...,-,-,-,-,-,-,-,-,-,GESTÃO AMBIENTAL (BACHARELADO)